[project]
name = "bigraph-schema"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.1",
    "parsimonious>=0.10.0",
    "pint>=0.24.4",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]
